name: Frontend CI - Dev

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend

      - name: Build Next.js app
        run: npm run build
        working-directory: ./frontend

        # To ensure code quality and catch bugs before merging:
      - name: Run Linter
        run: npm run lint
        working-directory: ./frontend

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/.next
